<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZUh3Jr9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZUh3Jr9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZUh3Jr9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZUh3Jr9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZUh3Jr9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZUh3Jr9',
    'container.build_id' => 'bfc8621a',
    'container.build_time' => 1574096362,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZUh3Jr9');
